version: '3'
services:
 mssql:
   image: 'microsoft/mssql-server-linux:2017-latest'
   container_name: my-mssql
   ports:
   - '1433:1433'
   environment:
   - ACCEPT_EULA=Y
   - 'SA_PASSWORD=EmergingSystems1'